# GET TABLES

In [1]:
import numpy as np
import pandas as pd
import sqlite3

### GET

In [2]:
dow_url = 'https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average'
sp5_url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
etf_url = 'https://etfdb.com/compare/volume/'

dow_raw = pd.read_html(dow_url)[1]
sp5_raw = pd.read_html(sp5_url)[0]
etf_raw = pd.read_html(etf_url)[0]

### FORMAT

In [3]:
dow_table =  pd.DataFrame({
    'Symbol': dow_raw['Symbol'].str.replace('.', '-')})

sp5_table =  pd.DataFrame({
    'Symbol': sp5_raw['Symbol'].str.replace('.', '-'),
    'Name': sp5_raw['Security'],
    'Sector': sp5_raw['GICS Sector'],
    'Industry': sp5_raw['GICS Sub-Industry']})

dow_table = dow_table.merge(sp5_table)

etf_table =  pd.DataFrame({
    'Symbol': etf_raw['Symbol'],
    'Name': etf_raw['Name']})

display(dow_table)
display(sp5_table)
display(etf_table)

,Symbol,Name,Sector,Industry
0,MMM,3M,Industrials,Industrial Conglomerates
1,AXP,American Express,Financials,Consumer Finance
2,AMGN,Amgen,Health Care,Biotechnology
3,AAPL,Apple,Information Technology,"Technology Hardware, Storage & Peripherals"
4,BA,Boeing,Industrials,Aerospace & Defense
5,CAT,Caterpillar,Industrials,Construction Machinery & Heavy Trucks
6,CVX,Chevron,Energy,Integrated Oil & Gas
7,CSCO,Cisco,Information Technology,Communications Equipment
8,KO,Coca-Cola,Consumer Staples,Soft Drinks
9,DIS,Disney,Communication Services,Movies & Entertainment
10,DOW,Dow,Materials,Commodity Chemicals
11,GS,Goldman Sachs,Financials,Investment Banking & Brokerage
12,HD,Home Depot,Consumer Discretionary,Home Improvement Retail
13,HON,Honeywell,Industrials,Industrial Conglomerates
14,IBM,IBM,Information Technology,IT Consulting & Other Services
15,INTC,Intel,Information Technology,Semiconductors
16,JNJ,Johnson & Johnson,Health Care,Pharmaceuticals
17,JPM,JPMorgan Chase,Financials,Diversified Banks
18,MCD,McDonald's,Consumer Discretionary,Restaurants
19,MRK,Merck,Health Care,Pharmaceuticals
20,MSFT,Microsoft,Information Technology,Systems Software
21,NKE,Nike,Consumer Discretionary,"Apparel, Accessories & Luxury Goods"
22,PG,Procter & Gamble,Consumer Staples,Personal Products
23,CRM,Salesforce,Information Technology,Application Software
24,TRV,Travelers,Financials,Property & Casualty Insurance
25,UNH,UnitedHealth Group,Health Care,Managed Health Care
26,VZ,Verizon,Communication Services,Integrated Telecommunication Services
27,V,Visa,Information Technology,Data Processing & Outsourced Services
28,WBA,Walgreens Boots Alliance,Consumer Staples,Drug Retail
29,WMT,Walmart,Consumer Staples,Hypermarkets & Super Centers

,Symbol,Name,Sector,Industry
0,MMM,3M,Industrials,Industrial Conglomerates
1,AOS,A. O. Smith,Industrials,Building Products
2,ABT,Abbott,Health Care,Health Care Equipment
3,ABBV,AbbVie,Health Care,Pharmaceuticals
4,ABMD,Abiomed,Health Care,Health Care Equipment
...,...,...,...,...
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants
500,ZBRA,Zebra,Information Technology,Electronic Equipment & Instruments
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment
502,ZION,Zions Bancorp,Financials,Regional Banks
503,ZTS,Zoetis,Health Care,Pharmaceuticals

   Symbol                                        Name
0    TQQQ                      ProShares UltraPro QQQ
1     SPY                      SPDR S&P 500 ETF Trust
2    SQQQ                ProShares UltraPro Short QQQ
3    UVXY  ProShares Ultra VIX Short-Term Futures ETF
4     QQQ                           Invesco QQQ Trust
..    ...                                         ...
95   SPDW    SPDR Portfolio Developed World ex-US ETF
96   ICLN             iShares Global Clean Energy ETF
97    ERY        Direxion Daily Energy Bear 2X Shares
98   SCHP                        Schwab U.S. TIPS ETF
99    XRT                         SPDR S&P Retail ETF

[100 rows x 2 columns]

### SAVE

In [4]:
# ! rm market.db
# con = sqlite3.connect('market.db')

# dow_table.to_sql('dow_table', con, index=False, if_exists='replace')
# sp5_table.to_sql('sp5_table', con, index=False, if_exists='replace')
# etf_table.to_sql('etf_table', con, index=False, if_exists='replace')